Import neccessary libraries

In [2]:
import pandas as pd 
import numpy as np
import matplotlib as plt

Check current directory

In [3]:
import os
print(os.getcwd())
os.listdir()

/Users/arajlymbakenova/Documents/Kaggle/BreastCancerDatasetAnalysis/general

['basic.ipynb']

Define patient_df for the patient profile dataset, see general info

In [4]:
patient_df = pd.read_csv('../datasets/patient_profiles.csv', delimiter=',')
patient_df.head()

,Patient_ID,Age_at_Diagnosis,Molecular_Subtype,BRCA_Mutation,Tumor_Grade,Initial_Tumor_Size_mm
0,BC-00001,60,Triple-Negative,0,1,15.11
1,BC-00002,53,HER2-Enriched,0,1,11.67
2,BC-00003,62,Luminal A,0,1,44.78
3,BC-00004,73,Luminal A,0,1,11.24
4,BC-00005,52,Luminal A,1,1,12.90

In [5]:
patient_df.columns

Index(['Patient_ID', 'Age_at_Diagnosis', 'Molecular_Subtype', 'BRCA_Mutation',
       'Tumor_Grade', 'Initial_Tumor_Size_mm'],
      dtype='object')

In [6]:
patient_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             2500 non-null   object
 1   Age_at_Diagnosis       2500 non-null   int64
 2   Molecular_Subtype      2500 non-null   object
 3   BRCA_Mutation          2500 non-null   int64
 4   Tumor_Grade            2500 non-null   int64
 5   Initial_Tumor_Size_mm  2500 non-null   float64
dtypes: float64(1), int64(3), object(2)
memory usage: 117.3+ KB

In [7]:
patient_df.describe()

       Age_at_Diagnosis  BRCA_Mutation  Tumor_Grade  Initial_Tumor_Size_mm
count       2500.000000    2500.000000  2500.000000            2500.000000
mean          54.906800       0.120400     2.095600              29.573448
std           11.797872       0.325494     0.688949              20.654814
min           16.000000       0.000000     1.000000               1.020000
25%           47.000000       0.000000     2.000000              14.410000
50%           55.000000       0.000000     2.000000              24.945000
75%           63.000000       0.000000     3.000000              39.780000
max          101.000000       1.000000     3.000000             145.110000

In [8]:
treatment_df = pd.read_csv('../datasets/treatment_journey.csv', delimiter=',')
treatment_df.head()

,Patient_ID,Treatment_Round,Regimen,Tumor_Shrinkage_Pct,CA15_3_Level,Side_Effect_Severity,Response_Status
0,BC-00001,1,AC-T (Adriamycin/Cytoxan/Taxol),37.36,28.13,4,Partial
1,BC-00001,2,Docetaxel + Carboplatin,22.61,21.77,7,Partial
2,BC-00002,1,AC-T (Adriamycin/Cytoxan/Taxol),85.66,10.99,6,Complete
3,BC-00003,1,AC-T (Adriamycin/Cytoxan/Taxol),30.25,61.34,9,Partial
4,BC-00003,2,Exemestane,32.34,41.51,3,Partial

In [9]:
treatment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Patient_ID            4981 non-null   object
 1   Treatment_Round       4981 non-null   int64
 2   Regimen               4981 non-null   object
 3   Tumor_Shrinkage_Pct   4981 non-null   float64
 4   CA15_3_Level          4981 non-null   float64
 5   Side_Effect_Severity  4981 non-null   int64
 6   Response_Status       4981 non-null   object
dtypes: float64(2), int64(2), object(3)
memory usage: 272.5+ KB

In [10]:
treatment_df.describe()

,Treatment_Round,Tumor_Shrinkage_Pct,CA15_3_Level,Side_Effect_Severity
count,4981.000000,4981.000000,4981.000000,4981.000000
mean,1.498093,37.701899,36.443333,5.555912
std,0.500047,14.696995,16.675000,1.985170
min,1.000000,0.000000,-1.490000,2.000000
25%,1.000000,27.640000,23.720000,4.000000
50%,1.000000,37.220000,33.910000,6.000000
75%,2.000000,46.550000,46.960000,7.000000
max,2.000000,103.240000,105.140000,9.000000

In [11]:
analysis_df = treatment_df.merge(patient_df, on='Patient_ID', how='left')

In [12]:
analysis_df.head(10)

,Patient_ID,Treatment_Round,Regimen,Tumor_Shrinkage_Pct,CA15_3_Level,Side_Effect_Severity,Response_Status,Age_at_Diagnosis,Molecular_Subtype,BRCA_Mutation,Tumor_Grade,Initial_Tumor_Size_mm
0,BC-00001,1,AC-T (Adriamycin/Cytoxan/Taxol),37.36,28.13,4,Partial,60,Triple-Negative,0,1,15.11
1,BC-00001,2,Docetaxel + Carboplatin,22.61,21.77,7,Partial,60,Triple-Negative,0,1,15.11
2,BC-00002,1,AC-T (Adriamycin/Cytoxan/Taxol),85.66,10.99,6,Complete,53,HER2-Enriched,0,1,11.67
3,BC-00003,1,AC-T (Adriamycin/Cytoxan/Taxol),30.25,61.34,9,Partial,62,Luminal A,0,1,44.78
4,BC-00003,2,Exemestane,32.34,41.51,3,Partial,62,Luminal A,0,1,44.78
5,BC-00004,1,AC-T (Adriamycin/Cytoxan/Taxol),43.76,25.55,8,Partial,73,Luminal A,0,1,11.24
6,BC-00004,2,Exemestane,16.06,21.45,5,Refractory,73,Luminal A,0,1,11.24
7,BC-00005,1,AC-T (Adriamycin/Cytoxan/Taxol),30.75,56.87,8,Partial,52,Luminal A,1,1,12.90
8,BC-00005,2,Exemestane,62.55,21.30,7,Partial,52,Luminal A,1,1,12.90
9,BC-00006,1,AC-T (Adriamycin/Cytoxan/Taxol),51.34,21.52,6,Partial,52,Luminal A,0,3,23.51

In [13]:
analysis_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             4981 non-null   object
 1   Treatment_Round        4981 non-null   int64
 2   Regimen                4981 non-null   object
 3   Tumor_Shrinkage_Pct    4981 non-null   float64
 4   CA15_3_Level           4981 non-null   float64
 5   Side_Effect_Severity   4981 non-null   int64
 6   Response_Status        4981 non-null   object
 7   Age_at_Diagnosis       4981 non-null   int64
 8   Molecular_Subtype      4981 non-null   object
 9   BRCA_Mutation          4981 non-null   int64
 10  Tumor_Grade            4981 non-null   int64
 11  Initial_Tumor_Size_mm  4981 non-null   float64
dtypes: float64(3), int64(5), object(4)
memory usage: 467.1+ KB